# Generated by Django 3.0.8 on 2020-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='collectionTitle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
