# Generated by Django 3.0.8 on 2020-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200705_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collectionTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
