# Generated by Django 3.0.8 on 2020-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200705_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
