# Generated by Django 3.0.8 on 2020-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
